name: release-please

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          config-file: release-please-config.json
          token: ${{ secrets.GH_PAT }}